apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: alicloud/disk
  labels:
    app: {{ template "gitlab-runner.fullname" . }}
  name: {{ template "gitlab-runner.fullname" . }}-gitlab-runner-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-efficiency
status: {}
